# Generated by Django 4.2.30 on 2026-06-03 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sprites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Nova Mesa', max_length=120)),
                ('Slug', models.SlugField(blank=True, max_length=32, unique=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-UpdatedAt', 'CreatedAt'),
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Novo Mapa', max_length=120)),
                ('Order', models.PositiveSmallIntegerField(default=0)),
                ('GridMode', models.CharField(choices=[('square', 'Quadrada'), ('free', 'Livre')], default='square', max_length=8)),
                ('WidthPx', models.PositiveIntegerField(default=1600)),
                ('HeightPx', models.PositiveIntegerField(default=1200)),
                ('GridSize', models.PositiveSmallIntegerField(default=64)),
                ('ShowGrid', models.BooleanField(default=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabletop_backgrounds', to='sprites.spriteasset')),
                ('Table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabletop.gametable')),
            ],
            options={
                'ordering': ('Order', 'CreatedAt'),
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kind', models.CharField(choices=[('player', 'Jogador'), ('enemy', 'Inimigo'), ('npc', 'NPC'), ('object', 'Objeto')], default='enemy', max_length=8)),
                ('Label', models.CharField(blank=True, max_length=80)),
                ('X', models.IntegerField(default=0)),
                ('Y', models.IntegerField(default=0)),
                ('GridWidth', models.PositiveSmallIntegerField(default=1)),
                ('GridHeight', models.PositiveSmallIntegerField(default=1)),
                ('MovableByPlayers', models.BooleanField(default=False)),
                ('Hidden', models.BooleanField(default=False)),
                ('Order', models.PositiveSmallIntegerField(default=0)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabletop.map')),
                ('SpriteAsset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabletop_tokens', to='sprites.spriteasset')),
            ],
            options={
                'ordering': ('Order', 'CreatedAt'),
            },
        ),
        migrations.AddField(
            model_name='gametable',
            name='ActiveMap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tabletop.map'),
        ),
        migrations.AddField(
            model_name='gametable',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FogRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.IntegerField(default=0)),
                ('Y', models.IntegerField(default=0)),
                ('Width', models.PositiveIntegerField(default=0)),
                ('Height', models.PositiveIntegerField(default=0)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabletop.map')),
            ],
            options={
                'ordering': ('CreatedAt',),
            },
        ),
    ]
