# Generated by Django 4.2.30 on 2026-06-03 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprites', '0001_initial'),
        ('tabletop', '0002_square_to_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='Rotation',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TerrainCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q', models.IntegerField()),
                ('R', models.IntegerField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabletop.map')),
                ('SpriteAsset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabletop_terrain', to='sprites.spriteasset')),
            ],
            options={
                'ordering': ('CreatedAt',),
            },
        ),
        migrations.AddConstraint(
            model_name='terraincell',
            constraint=models.UniqueConstraint(fields=('Map', 'Q', 'R'), name='unique_terrain_cell_per_map'),
        ),
    ]
