# Generated by Django 4.2.30 on 2026-06-05 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabletop', '0003_terrain_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='terraincell',
            name='Terrain',
            field=models.CharField(default='stone', max_length=16),
        ),
        migrations.AddField(
            model_name='token',
            name='Conditions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='token',
            name='Faction',
            field=models.CharField(choices=[('party', 'Grupo'), ('ally', 'Aliado'), ('neutral', 'Neutro'), ('enemy', 'Inimigo')], default='enemy', max_length=8),
        ),
        migrations.AddField(
            model_name='token',
            name='HP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='token',
            name='MaxHP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='token',
            name='Size',
            field=models.CharField(choices=[('sm', 'Pequeno'), ('md', 'Médio'), ('lg', 'Grande'), ('xl', 'Enorme')], default='md', max_length=2),
        ),
        migrations.CreateModel(
            name='FogCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q', models.IntegerField()),
                ('R', models.IntegerField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabletop.map')),
            ],
            options={
                'ordering': ('CreatedAt',),
            },
        ),
        migrations.AddConstraint(
            model_name='fogcell',
            constraint=models.UniqueConstraint(fields=('Map', 'Q', 'R'), name='unique_fog_cell_per_map'),
        ),
    ]
