# Generated by Django 4.2.11 on 2024-04-09 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Strength', models.IntegerField(blank=True, default=0, null=True)),
                ('Dexterity', models.IntegerField(blank=True, default=0, null=True)),
                ('Constitution', models.IntegerField(blank=True, default=0, null=True)),
                ('Intelligence', models.IntegerField(blank=True, default=0, null=True)),
                ('Wisdom', models.IntegerField(blank=True, default=0, null=True)),
                ('Charisma', models.IntegerField(blank=True, default=0, null=True)),
                ('StrengthStatMod', models.IntegerField(blank=True, default=0, null=True)),
                ('DexterityStatMod', models.IntegerField(blank=True, default=0, null=True)),
                ('ConstitutionStatMod', models.IntegerField(blank=True, default=0, null=True)),
                ('IntelligenceStatMod', models.IntegerField(blank=True, default=0, null=True)),
                ('WisdomStatMod', models.IntegerField(blank=True, default=0, null=True)),
                ('CharismaStatMod', models.IntegerField(blank=True, default=0, null=True)),
                ('StrengthTemp', models.IntegerField(blank=True, default=0, null=True)),
                ('DexterityTemp', models.IntegerField(blank=True, default=0, null=True)),
                ('ConstitutionTemp', models.IntegerField(blank=True, default=0, null=True)),
                ('IntelligenceTemp', models.IntegerField(blank=True, default=0, null=True)),
                ('WisdomTemp', models.IntegerField(blank=True, default=0, null=True)),
                ('CharismaTemp', models.IntegerField(blank=True, default=0, null=True)),
                ('StrengthModTemp', models.IntegerField(blank=True, default=0, null=True)),
                ('DexterityModTemp', models.IntegerField(blank=True, default=0, null=True)),
                ('ConstitutionModTemp', models.IntegerField(blank=True, default=0, null=True)),
                ('IntelligenceModTemp', models.IntegerField(blank=True, default=0, null=True)),
                ('WisdomModTemp', models.IntegerField(blank=True, default=0, null=True)),
                ('CharismaModTemp', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Class', models.CharField(blank=True, max_length=200, null=True)),
                ('Level', models.CharField(blank=True, max_length=200, null=True)),
                ('Race', models.CharField(blank=True, max_length=200, null=True)),
                ('Alignment', models.CharField(blank=True, max_length=200, null=True)),
                ('Deity', models.CharField(blank=True, max_length=200, null=True)),
                ('Size', models.CharField(blank=True, max_length=200, null=True)),
                ('Age', models.CharField(blank=True, max_length=200, null=True)),
                ('Sex', models.CharField(blank=True, max_length=200, null=True)),
                ('Heigth', models.CharField(blank=True, max_length=200, null=True)),
                ('Weight', models.CharField(blank=True, max_length=200, null=True)),
                ('Eye', models.CharField(blank=True, max_length=200, null=True)),
                ('Hair', models.CharField(blank=True, max_length=200, null=True)),
                ('Skin', models.CharField(blank=True, max_length=200, null=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('CharacterStats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.characterstats')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-UpdatedAt', 'CreatedAt'],
            },
        ),
    ]
