# Generated by Django 4.2.11 on 2024-04-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterskill',
            name='SkillIsActive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
