# Generated by Django 4.2.11 on 2024-04-09 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='CharacterStats',
        ),
        migrations.RemoveField(
            model_name='characterstats',
            name='id',
        ),
        migrations.AddField(
            model_name='characterstats',
            name='Character',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.character'),
            preserve_default=False,
        ),
    ]
