# Generated by Django 4.2.30 on 2026-06-02 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Combatant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Kind', models.CharField(choices=[('player', 'Jogador'), ('npc', 'NPC'), ('enemy', 'Inimigo')], default='enemy', max_length=8)),
                ('Initiative', models.IntegerField(default=0)),
                ('DamageTaken', models.IntegerField(default=0)),
                ('ArmorClass', models.IntegerField(blank=True, null=True)),
                ('Effects', models.CharField(blank=True, max_length=200)),
                ('Notes', models.CharField(blank=True, max_length=300)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-Initiative', 'CreatedAt'),
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Novo Encontro', max_length=120)),
                ('Slug', models.SlugField(blank=True, max_length=32, unique=True)),
                ('Round', models.PositiveIntegerField(default=1)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('ActiveCombatant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initiative.combatant')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-UpdatedAt', 'CreatedAt'),
            },
        ),
        migrations.AddField(
            model_name='combatant',
            name='Encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiative.encounter'),
        ),
    ]
