# Generated by Django 4.2.30 on 2026-06-02 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprites', '0001_initial'),
        ('initiative', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatant',
            name='SpriteAsset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiative_combatants', to='sprites.spriteasset'),
        ),
    ]
