# Generated by Django 4.2.30 on 2026-05-30 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_skill_specialization_and_key_ability'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterCompanion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=200)),
                ('Name', models.CharField(blank=True, max_length=200)),
                ('Species', models.CharField(blank=True, max_length=200)),
                ('HitPoints', models.IntegerField(default=0)),
                ('ArmorClass', models.IntegerField(default=0)),
                ('Speed', models.CharField(blank=True, max_length=50)),
                ('Skills', models.TextField(blank=True)),
                ('Feats', models.TextField(blank=True)),
                ('SpecialAbilities', models.TextField(blank=True)),
                ('Notes', models.TextField(blank=True)),
                ('Character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character')),
            ],
        ),
    ]
