# Generated by Django 4.2.30 on 2026-05-30 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_charactercompanion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterFaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200)),
                ('Reputation', models.CharField(blank=True, max_length=200)),
                ('Influence', models.CharField(blank=True, max_length=200)),
                ('Risk', models.CharField(blank=True, max_length=200)),
                ('Notes', models.TextField(blank=True)),
                ('Character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=200)),
                ('Party', models.CharField(blank=True, max_length=200)),
                ('Reward', models.CharField(blank=True, max_length=200)),
                ('Deadline', models.CharField(blank=True, max_length=200)),
                ('Status', models.CharField(blank=True, max_length=200)),
                ('Notes', models.TextField(blank=True)),
                ('Character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200)),
                ('Location', models.CharField(blank=True, max_length=200)),
                ('Relationship', models.CharField(blank=True, max_length=200)),
                ('Favor', models.CharField(blank=True, max_length=200)),
                ('Notes', models.TextField(blank=True)),
                ('Character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character')),
            ],
        ),
    ]
