# Generated by Django 4.2.30 on 2026-05-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_reputation_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterspell',
            name='SDRSpellId',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
