# Generated by Django 4.2.30 on 2026-06-02 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_characterspell_sdrspellid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSummon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200)),
                ('SpellOrigin', models.CharField(blank=True, max_length=100)),
                ('Level', models.IntegerField(default=0)),
                ('HitPointsMax', models.IntegerField(default=0)),
                ('HitPointsCurrent', models.IntegerField(default=0)),
                ('ArmorClass', models.IntegerField(default=0)),
                ('AttackBonus', models.CharField(blank=True, max_length=200)),
                ('Damage', models.CharField(blank=True, max_length=200)),
                ('SpecialAbility', models.CharField(blank=True, max_length=500)),
                ('RoundsTotal', models.IntegerField(default=0)),
                ('RoundsRemaining', models.IntegerField(default=0)),
                ('SdrMonsterName', models.CharField(blank=True, max_length=200)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character')),
            ],
            options={
                'ordering': ('-RoundsRemaining', 'CreatedAt'),
            },
        ),
    ]
