# Generated by Django 4.2.30 on 2026-06-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0008_charactersummon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charactersummon',
            options={'ordering': ('-Highlighted', '-RoundsRemaining', 'CreatedAt')},
        ),
        migrations.AddField(
            model_name='charactersummon',
            name='Highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
