# Generated by Django 4.2.30 on 2026-06-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0009_summon_highlighted'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterstatus',
            name='CurrentHitPoints',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='characterstatus',
            name='TemporaryHitPoints',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
