# Generated by Django 4.2.30 on 2026-06-02 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0010_status_hitpoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterBuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('IsActive', models.BooleanField(default=False)),
                ('StrengthBonus', models.IntegerField(default=0)),
                ('DexterityBonus', models.IntegerField(default=0)),
                ('ConstitutionBonus', models.IntegerField(default=0)),
                ('IntelligenceBonus', models.IntegerField(default=0)),
                ('WisdomBonus', models.IntegerField(default=0)),
                ('CharismaBonus', models.IntegerField(default=0)),
                ('AttackBonus', models.IntegerField(default=0)),
                ('ACBonus', models.IntegerField(default=0)),
                ('SaveBonus', models.IntegerField(default=0)),
                ('Notes', models.CharField(blank=True, max_length=200)),
                ('Character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character')),
            ],
        ),
    ]
