# Generated by Codex on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0011_characterbuff'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersummon',
            name='Attack',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='charactersummon',
            name='BaseAttackBonus',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='charactersummon',
            name='FullAttack',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charactersummon',
            name='Grapple',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='charactersummon',
            name='Initiative',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='charactersummon',
            name='Size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='charactersummon',
            name='Skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charactersummon',
            name='Speed',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
