# Generated by Django 4.2.30 on 2026-06-02 23:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sprites.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpriteAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('Category', models.CharField(choices=[('class', 'Classe'), ('monster', 'Monstro'), ('character', 'Personagem'), ('companion', 'Companheiro'), ('map_token', 'Miniatura de mapa'), ('map_tile', 'Tile de mapa'), ('item', 'Item'), ('generic', 'Generico')], db_index=True, default='generic', max_length=24)),
                ('OriginalImage', models.FileField(blank=True, upload_to=sprites.models.sprite_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'webp', 'gif', 'svg'))])),
                ('AltText', models.CharField(blank=True, max_length=180)),
                ('Visibility', models.CharField(choices=[('public', 'Publico'), ('owner', 'Apenas dono')], db_index=True, default='public', max_length=12)),
                ('Width', models.PositiveIntegerField(blank=True, default=0)),
                ('Height', models.PositiveIntegerField(blank=True, default=0)),
                ('FileSize', models.PositiveIntegerField(blank=True, default=0)),
                ('Checksum', models.CharField(blank=True, db_index=True, max_length=64)),
                ('DefaultGridWidth', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('DefaultGridHeight', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('AnchorX', models.DecimalField(decimal_places=3, default=0.5, max_digits=4)),
                ('AnchorY', models.DecimalField(decimal_places=3, default=0.5, max_digits=4)),
                ('IsActive', models.BooleanField(db_index=True, default=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('Category', 'Name'),
            },
        ),
        migrations.CreateModel(
            name='SpriteVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Variant', models.CharField(choices=[('thumb_64', 'Thumb 64'), ('icon_96', 'Icone 96'), ('token_128', 'Token 128'), ('token_256', 'Token 256'), ('portrait_320', 'Retrato 320'), ('portrait_640', 'Retrato 640')], db_index=True, max_length=24)),
                ('File', models.FileField(blank=True, upload_to=sprites.models.sprite_variant_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'webp', 'gif', 'svg'))])),
                ('Width', models.PositiveIntegerField(blank=True, default=0)),
                ('Height', models.PositiveIntegerField(blank=True, default=0)),
                ('Format', models.CharField(blank=True, max_length=16)),
                ('FileSize', models.PositiveIntegerField(blank=True, default=0)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('SpriteAsset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='sprites.spriteasset')),
            ],
            options={
                'ordering': ('SpriteAsset', 'Variant'),
            },
        ),
        migrations.CreateModel(
            name='SpriteBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TargetType', models.CharField(choices=[('sdr_class', 'Classe SDR'), ('sdr_monster', 'Monstro SDR'), ('combatant_kind', 'Tipo de combatente'), ('character_class', 'Classe da ficha'), ('companion_species', 'Especie de companheiro')], db_index=True, max_length=32)),
                ('TargetKey', models.CharField(db_index=True, max_length=160)),
                ('Purpose', models.CharField(choices=[('class_icon', 'Icone de classe'), ('class_portrait', 'Retrato de classe'), ('monster_token', 'Token de monstro'), ('monster_portrait', 'Retrato de monstro'), ('initiative_token', 'Token de iniciativa'), ('map_token', 'Token de mapa'), ('map_tile', 'Tile de mapa')], db_index=True, max_length=32)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('SpriteAsset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='sprites.spriteasset')),
            ],
            options={
                'ordering': ('TargetType', 'TargetKey', 'Purpose'),
            },
        ),
        migrations.AddConstraint(
            model_name='spritevariant',
            constraint=models.UniqueConstraint(fields=('SpriteAsset', 'Variant'), name='unique_sprite_variant_per_asset'),
        ),
        migrations.AddIndex(
            model_name='spritebinding',
            index=models.Index(fields=['TargetType', 'TargetKey', 'Purpose'], name='sprites_spr_TargetT_9a2523_idx'),
        ),
        migrations.AddConstraint(
            model_name='spritebinding',
            constraint=models.UniqueConstraint(fields=('TargetType', 'TargetKey', 'Purpose'), name='unique_sprite_binding_target_purpose'),
        ),
        migrations.AddIndex(
            model_name='spriteasset',
            index=models.Index(fields=['Category', 'IsActive'], name='sprites_spr_Categor_cca48c_idx'),
        ),
        migrations.AddIndex(
            model_name='spriteasset',
            index=models.Index(fields=['Visibility', 'IsActive'], name='sprites_spr_Visibil_6326ee_idx'),
        ),
    ]
