import tempfile
import math

from django.contrib.auth.models import User
from django.core.files.uploadedfile import SimpleUploadedFile
from django.test import SimpleTestCase, TestCase, override_settings
from django.urls import reverse

from sprites.models import SpriteAsset

from .calculations import (
    axial_to_pixel, hex_dimensions, nearest_hex_center, point_in_rect, snap_to_grid, token_visible_to,
)
from .models import FogRegion, GameTable, Map, Token


# 1x1 PNG válido (Pillow lê dimensões; sem Pillow, o upload ainda funciona).
PNG_1x1 = (
    b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01\x08\x06'
    b'\x00\x00\x00\x1f\x15\xc4\x89\x00\x00\x00\nIDATx\x9cc\x00\x01\x00\x00\x05'
    b'\x00\x01\r\n-\xb4\x00\x00\x00\x00IEND\xaeB`\x82'
)


class _Tok:
    """Stub leve p/ testar token_visible_to sem tocar o DB."""
    def __init__(self, x, y, hidden=False):
        self.X, self.Y, self.Hidden = x, y, hidden


class _Fog:
    def __init__(self, x, y, w, h):
        self.X, self.Y, self.Width, self.Height = x, y, w, h


class CalcTests(SimpleTestCase):
    def test_hex_dimensions_pointy_top(self):
        d = hex_dimensions(64)
        # R = 64/sqrt(3); flat-to-flat width = GridSize.
        self.assertAlmostEqual(d['radius'], 64 / math.sqrt(3), places=3)
        self.assertAlmostEqual(d['width'], 64, places=3)
        self.assertAlmostEqual(d['height'], 2 * 64 / math.sqrt(3), places=3)
        self.assertAlmostEqual(d['col_spacing'], 64, places=3)
        self.assertAlmostEqual(d['row_spacing'], 1.5 * 64 / math.sqrt(3), places=3)

    def test_nearest_hex_center_origin(self):
        self.assertEqual(nearest_hex_center(3, -2, 64), (0, 0))

    def test_axial_to_pixel_matches_pointy_top_geometry(self):
        self.assertEqual(axial_to_pixel(1, -2, 64), (0, -111))

    def test_nearest_hex_center_is_idempotent_on_a_center(self):
        cx, cy = nearest_hex_center(120, 90, 64)
        self.assertEqual(nearest_hex_center(cx, cy, 64), (cx, cy))

    def test_snap_hex_returns_a_hex_center(self):
        self.assertEqual(snap_to_grid(120, 90, 64, 'hex'), nearest_hex_center(120, 90, 64))

    def test_snap_free_is_identity(self):
        self.assertEqual(snap_to_grid(123, 77, 64, 'free'), (123, 77))

    def test_snap_without_size_is_identity(self):
        self.assertEqual(snap_to_grid(123, 77, 0, 'hex'), (123, 77))

    def test_point_in_rect(self):
        self.assertTrue(point_in_rect(50, 50, 0, 0, 100, 100))
        self.assertFalse(point_in_rect(150, 50, 0, 0, 100, 100))

    def test_visibility_owner_sees_everything(self):
        self.assertTrue(token_visible_to(_Tok(50, 50, hidden=True), [_Fog(0, 0, 100, 100)], True))

    def test_visibility_player_hidden_and_under_fog(self):
        self.assertFalse(token_visible_to(_Tok(10, 10, hidden=True), [], False))
        self.assertFalse(token_visible_to(_Tok(50, 50), [_Fog(0, 0, 100, 100)], False))
        self.assertTrue(token_visible_to(_Tok(500, 500), [_Fog(0, 0, 100, 100)], False))

    def test_hex_distance_axial(self):
        from .calculations import hex_distance
        self.assertEqual(hex_distance(0, 0, 0, 0), 0)
        self.assertEqual(hex_distance(0, 0, 3, 0), 3)
        self.assertEqual(hex_distance(0, 0, 0, 3), 3)
        self.assertEqual(hex_distance(0, 0, 2, -1), 2)
        self.assertEqual(hex_distance(2, -1, 0, 0), 2)

    def test_hex_disk_radii(self):
        from .calculations import hex_disk
        self.assertEqual(len(hex_disk(0, 0, 0)), 1)
        self.assertEqual(len(hex_disk(0, 0, 1)), 7)
        self.assertEqual(len(hex_disk(0, 0, 2)), 19)
        self.assertEqual(len(hex_disk(0, 0, 3)), 37)
        self.assertIn((0, 0), hex_disk(0, 0, 1))

    def test_hex_line_no_gaps(self):
        from .calculations import hex_line, hex_distance
        line = hex_line(0, 0, 3, 0)
        self.assertEqual(line[0], (0, 0))
        self.assertEqual(line[-1], (3, 0))
        self.assertEqual(len(line), 4)
        diag = hex_line(0, 0, 2, -1)
        self.assertEqual(len(diag), hex_distance(0, 0, 2, -1) + 1)

    def test_pixel_to_axial_roundtrip(self):
        from .calculations import pixel_to_axial
        for q, r in [(0, 0), (3, -2), (-1, 4), (5, 5)]:
            x, y = axial_to_pixel(q, r, 64)
            self.assertEqual(pixel_to_axial(x, y, 64), (q, r))


class ModelTests(TestCase):
    def setUp(self):
        self.owner = User.objects.create_user('owner', password='x' * 12)

    def test_slug_autogenerated_and_unique(self):
        a = GameTable.objects.create(Owner=self.owner, Name='A')
        b = GameTable.objects.create(Owner=self.owner, Name='B')
        self.assertTrue(a.Slug and b.Slug)
        self.assertNotEqual(a.Slug, b.Slug)

    def test_default_movable_by_kind(self):
        self.assertTrue(Token.default_movable_for_kind(Token.PLAYER))
        self.assertFalse(Token.default_movable_for_kind(Token.ENEMY))
        self.assertFalse(Token.default_movable_for_kind(Token.OBJECT))


class GridMigrationTests(TestCase):
    def test_new_map_defaults_to_hex(self):
        owner = User.objects.create_user('gm2', password='x' * 12)
        table = GameTable.objects.create(Owner=owner, Name='Mesa')
        m = Map.objects.create(Table=table, Name='Cena')
        self.assertEqual(m.GridMode, Map.HEX)


class TerrainPaletteTests(SimpleTestCase):
    def test_palette_has_nine_unique_keys(self):
        from .terrains import TERRAINS, TERRAIN_KEYS, DEFAULT_TERRAIN
        self.assertEqual(len(TERRAINS), 9)
        self.assertEqual(len(set(TERRAIN_KEYS)), 9)
        self.assertEqual(DEFAULT_TERRAIN, 'stone')
        self.assertIn('water', TERRAIN_KEYS)

    def test_solid_terrains_have_color_textured_have_slug(self):
        from .terrains import TERRAINS
        by_id = {t['id']: t for t in TERRAINS}
        self.assertEqual(by_id['water']['kind'], 'color')
        self.assertTrue(by_id['water']['color'].startswith('#'))
        self.assertEqual(by_id['dungeon']['kind'], 'texture')
        self.assertTrue(by_id['dungeon']['slug'])


class SceneModelTests(TestCase):
    def setUp(self):
        self.user = User.objects.create_user('m', password='x')
        self.table = GameTable.objects.create(Owner=self.user, Name='T')
        self.map = Map.objects.create(Table=self.table, Name='C')

    def test_token_scene_fields_defaults(self):
        t = Token.objects.create(Map=self.map)
        self.assertEqual(t.Faction, Token.ENEMY_FACTION)
        self.assertEqual(t.Size, 'md')
        self.assertEqual(t.HP, 0)
        self.assertEqual(t.MaxHP, 0)
        self.assertEqual(t.Conditions, [])

    def test_fogcell_unique_per_map(self):
        from .models import FogCell
        FogCell.objects.create(Map=self.map, Q=1, R=2)
        with self.assertRaises(Exception):
            FogCell.objects.create(Map=self.map, Q=1, R=2)

    def test_terraincell_terrain_key(self):
        from .models import TerrainCell
        c = TerrainCell.objects.create(Map=self.map, Q=0, R=0, Terrain='grass')
        self.assertEqual(c.Terrain, 'grass')


class FactionDerivationTests(SimpleTestCase):
    def test_kind_to_faction_mapping(self):
        self.assertEqual(Token.KIND_TO_FACTION[Token.PLAYER], Token.PARTY)
        self.assertEqual(Token.KIND_TO_FACTION[Token.ENEMY], Token.ENEMY_FACTION)
        self.assertEqual(Token.KIND_TO_FACTION[Token.NPC], Token.NEUTRAL)
        self.assertEqual(Token.KIND_TO_FACTION[Token.OBJECT], Token.NEUTRAL)


class FogVisibilityTests(SimpleTestCase):
    def test_token_hidden_when_its_hex_is_fogged(self):
        from .calculations import token_hex_visible
        self.assertFalse(token_hex_visible(2, 1, {(2, 1)}, is_owner=False))
        self.assertTrue(token_hex_visible(2, 1, {(0, 0)}, is_owner=False))
        self.assertTrue(token_hex_visible(2, 1, {(2, 1)}, is_owner=True))


class SceneSerializerTests(TestCase):
    def setUp(self):
        self.user = User.objects.create_user('m', password='x')
        self.table = GameTable.objects.create(Owner=self.user, Name='T')
        self.map = Map.objects.create(Table=self.table, Name='C', GridSize=64)

    def test_serialize_scene_shape(self):
        from .serializers import serialize_scene
        from .models import TerrainCell, FogCell
        Token.objects.create(Map=self.map, Label='Lúmen', Faction='party', HP=18, MaxHP=24,
                             Size='md', Conditions=['blessed'], X=0, Y=0)
        TerrainCell.objects.create(Map=self.map, Q=1, R=0, Terrain='grass')
        FogCell.objects.create(Map=self.map, Q=2, R=2)
        data = serialize_scene(self.map, is_owner=True)
        self.assertEqual(data['grid']['size'], 64)
        self.assertEqual(data['terrain'], [{'q': 1, 'r': 0, 'terrain': 'grass'}])
        self.assertEqual(data['fog'], [{'q': 2, 'r': 2}])
        tok = data['tokens'][0]
        self.assertEqual(tok['faction'], 'party')
        self.assertEqual(tok['hp'], 18)
        self.assertEqual(tok['conditions'], ['blessed'])
        self.assertIn('q', tok)

    def test_live_serialize_hides_fogged_and_hidden(self):
        from .serializers import serialize_scene
        Token.objects.create(Map=self.map, Hidden=True, X=0, Y=0)
        data = serialize_scene(self.map, is_owner=False)
        self.assertEqual(data['tokens'], [])


class ApplyScenePayloadTests(TestCase):
    def setUp(self):
        self.user = User.objects.create_user('m', password='x')
        self.table = GameTable.objects.create(Owner=self.user, Name='T')
        self.map = Map.objects.create(Table=self.table, Name='C', GridSize=64)

    def test_apply_replaces_terrain_and_fog_and_upserts_tokens(self):
        from .serializers import apply_scene_payload
        from .models import TerrainCell, FogCell
        payload = {
            'name': 'Cripta',
            'grid': {'cols': 30, 'rows': 22},
            'terrain': [{'q': 0, 'r': 0, 'terrain': 'grass'}, {'q': 1, 'r': 0, 'terrain': 'water'}],
            'fog': [{'q': 5, 'r': 5}],
            'tokens': [{'tempId': 'n1', 'name': 'Orc', 'faction': 'enemy', 'q': 2, 'r': 1,
                        'hp': 10, 'maxHp': 12, 'size': 'md', 'conditions': [], 'kind': 'enemy'}],
        }
        apply_scene_payload(self.map, payload)
        self.map.refresh_from_db()
        self.assertEqual(self.map.Name, 'Cripta')
        self.assertEqual(TerrainCell.objects.filter(Map=self.map).count(), 2)
        self.assertEqual(FogCell.objects.filter(Map=self.map).count(), 1)
        self.assertEqual(Token.objects.filter(Map=self.map, Label='Orc').count(), 1)

    def test_apply_deletes_tokens_absent_from_payload(self):
        from .serializers import apply_scene_payload
        existing = Token.objects.create(Map=self.map, Label='Some')
        apply_scene_payload(self.map, {'tokens': [], 'terrain': [], 'fog': []})
        self.assertFalse(Token.objects.filter(id=existing.id).exists())

    def test_apply_returns_tempid_to_id_map(self):
        from .serializers import apply_scene_payload
        id_map = apply_scene_payload(self.map, {
            'tokens': [{'tempId': 'n7', 'name': 'Goblin', 'q': 0, 'r': 0}],
            'terrain': [], 'fog': [],
        })
        self.assertIn('n7', id_map)
        self.assertTrue(Token.objects.filter(id=id_map['n7']).exists())


class SceneSaveViewTests(TestCase):
    def setUp(self):
        self.user = User.objects.create_user('m', password='x')
        self.other = User.objects.create_user('o', password='x')
        self.table = GameTable.objects.create(Owner=self.user, Name='T')
        self.map = Map.objects.create(Table=self.table, Name='C', GridSize=64)

    def test_owner_can_save_scene(self):
        self.client.force_login(self.user)
        url = reverse('tabletop:scene-save', args=[self.table.Slug, self.map.id])
        resp = self.client.post(url, data={'scene': '{"terrain":[{"q":0,"r":0,"terrain":"grass"}],"fog":[],"tokens":[]}'})
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(self.map.terraincell_set.count(), 1)

    def test_non_owner_forbidden(self):
        self.client.force_login(self.other)
        url = reverse('tabletop:scene-save', args=[self.table.Slug, self.map.id])
        resp = self.client.post(url, data={'scene': '{"terrain":[],"fog":[],"tokens":[]}'})
        self.assertEqual(resp.status_code, 403)


class EditorShellTests(TestCase):
    def setUp(self):
        self.user = User.objects.create_user('m', password='x')
        self.table = GameTable.objects.create(Owner=self.user, Name='T')
        self.map = Map.objects.create(Table=self.table, Name='C', GridSize=64)
        self.table.ActiveMap = self.map
        self.table.save()

    def test_editor_embeds_scene_json(self):
        self.client.force_login(self.user)
        resp = self.client.get(reverse('tabletop:editor', args=[self.table.Slug, self.map.id]))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, 'id="tt-scene-data"')
        self.assertContains(resp, 'data-rich-editor="2"')

    def test_live_fragment_returns_json(self):
        resp = self.client.get(reverse('tabletop:live-fragment', args=[self.table.Slug]))
        self.assertEqual(resp['Content-Type'], 'application/json')
        import json as _j
        body = _j.loads(resp.content)
        self.assertIn('tokens', body)
        self.assertIn('terrain', body)


class _Base(TestCase):
    def setUp(self):
        self.owner = User.objects.create_user('owner', password='x' * 12)
        self.stranger = User.objects.create_user('stranger', password='x' * 12)
        self.table = GameTable.objects.create(Owner=self.owner, Name='Mesa')
        self.map = Map.objects.create(Table=self.table, Name='Cena', GridMode=Map.HEX, GridSize=64)
        self.table.ActiveMap = self.map
        self.table.save()

    def url(self, name, *args):
        return reverse('tabletop:' + name, args=[self.table.Slug, *args])


class PermissionTests(_Base):
    def test_table_view_public(self):
        resp = self.client.get(self.url('table'))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, 'Mesa')

    def test_manage_requires_owner(self):
        self.assertEqual(self.client.get(self.url('manage')).status_code, 403)  # anônimo
        self.client.force_login(self.stranger)
        self.assertEqual(self.client.get(self.url('manage')).status_code, 403)
        self.client.force_login(self.owner)
        self.assertEqual(self.client.get(self.url('manage')).status_code, 200)

    def test_add_map_owner_only(self):
        self.assertEqual(self.client.post(self.url('add-map'), {'Name': 'X'}).status_code, 403)
        self.client.force_login(self.owner)
        self.client.post(self.url('add-map'), {'Name': 'Nova', 'GridMode': 'free'})
        self.assertTrue(Map.objects.filter(Table=self.table, Name='Nova').exists())

    def test_set_active_switches_scene(self):
        self.client.force_login(self.owner)
        other = Map.objects.create(Table=self.table, Name='Outra')
        self.client.post(self.url('set-active', other.id))
        self.table.refresh_from_db()
        self.assertEqual(self.table.ActiveMap_id, other.id)


class TokenTests(_Base):
    def test_add_player_token_movable_by_default(self):
        self.client.force_login(self.owner)
        self.client.post(self.url('add-token'), {'MapId': self.map.id, 'Kind': 'player', 'Label': 'Heroi'})
        tok = Token.objects.get(Map=self.map, Label='Heroi')
        self.assertTrue(tok.MovableByPlayers)
        self.assertEqual(tok.Kind, Token.PLAYER)

    def test_add_enemy_token_not_movable(self):
        self.client.force_login(self.owner)
        self.client.post(self.url('add-token'), {'MapId': self.map.id, 'Kind': 'enemy'})
        self.assertFalse(Token.objects.get(Map=self.map).MovableByPlayers)


class MoveTests(_Base):
    def _player_token(self, movable=True, on_active=True):
        m = self.map if on_active else Map.objects.create(Table=self.table, Name='Inativa')
        return Token.objects.create(Map=m, Kind=Token.PLAYER, MovableByPlayers=movable, X=10, Y=10)

    def test_owner_moves_any_token_and_snaps(self):
        self.client.force_login(self.owner)
        tok = Token.objects.create(Map=self.map, Kind=Token.ENEMY, X=0, Y=0)
        resp = self.client.post(self.url('move-token', tok.id), {'X': 100, 'Y': 30})
        self.assertEqual(resp.status_code, 200)
        tok.refresh_from_db()
        self.assertEqual((tok.X, tok.Y), nearest_hex_center(100, 30, 64))

    def test_anonymous_moves_movable_token_on_active_map(self):
        tok = self._player_token(movable=True, on_active=True)
        resp = self.client.post(self.url('move-token', tok.id), {'X': 200, 'Y': 200})
        self.assertEqual(resp.status_code, 200)
        tok.refresh_from_db()
        self.assertEqual((tok.X, tok.Y), nearest_hex_center(200, 200, 64))

    def test_anonymous_cannot_move_enemy(self):
        tok = Token.objects.create(Map=self.map, Kind=Token.ENEMY, MovableByPlayers=False, X=0, Y=0)
        self.assertEqual(self.client.post(self.url('move-token', tok.id), {'X': 50, 'Y': 50}).status_code, 403)

    def test_anonymous_cannot_move_token_on_inactive_map(self):
        tok = self._player_token(movable=True, on_active=False)
        self.assertEqual(self.client.post(self.url('move-token', tok.id), {'X': 50, 'Y': 50}).status_code, 403)


class VisibilityTests(_Base):
    def test_player_fragment_hides_fogged_and_hidden_tokens(self):
        from .models import FogCell
        FogCell.objects.create(Map=self.map, Q=0, R=0)  # hex (0,0) coberto
        Token.objects.create(Map=self.map, Kind=Token.ENEMY, Label='Goblin', X=0, Y=0)       # no hex (0,0): sob névoa
        Token.objects.create(Map=self.map, Kind=Token.ENEMY, Label='Espreita', X=400, Y=400, Hidden=True)
        Token.objects.create(Map=self.map, Kind=Token.PLAYER, Label='Aragorn', X=400, Y=400)    # visível

        anon = self.client.get(self.url('live-fragment'))
        self.assertNotContains(anon, 'Goblin')
        self.assertNotContains(anon, 'Espreita')
        self.assertContains(anon, 'Aragorn')

        self.client.force_login(self.owner)
        owner = self.client.get(self.url('live-fragment'))
        self.assertContains(owner, 'Goblin')
        self.assertContains(owner, 'Espreita')


class RenderTests(_Base):
    def test_table_view_full_page_fragment_is_json(self):
        full = self.client.get(self.url('table'))
        self.assertContains(full, 'app-nav')              # estende main.html
        frag = self.client.get(self.url('live-fragment'))
        self.assertEqual(frag['Content-Type'], 'application/json')
        self.assertNotContains(frag, 'app-nav')           # só dados
        import json
        body = json.loads(frag.content)
        self.assertIn('tokens', body)
        self.assertIn('terrain', body)

    def test_owner_pages_render(self):
        self.client.force_login(self.owner)
        self.assertEqual(self.client.get(reverse('tabletop:home')).status_code, 200)
        self.assertEqual(self.client.get(self.url('editor', self.map.id)).status_code, 200)

    def test_editor_renders_scene_creator_chrome(self):
        self.client.force_login(self.owner)
        resp = self.client.get(self.url('editor', self.map.id))
        self.assertContains(resp, 'data-rich-editor="2"')
        self.assertContains(resp, 'id="sc-stage"')
        self.assertContains(resp, 'id="sc-canvas"')
        self.assertContains(resp, 'id="tt-scene-data"')
        self.assertContains(resp, 'sc-tooldock')

    def test_editor_token_palette_includes_items_and_markers(self):
        SpriteAsset.objects.create(Name='Closed Chest Item', Category=SpriteAsset.ITEM)
        SpriteAsset.objects.create(Name='Danger Marker', Category=SpriteAsset.GENERIC)
        SpriteAsset.objects.create(Name='Road Tile', Category=SpriteAsset.MAP_TILE)

        self.client.force_login(self.owner)
        resp = self.client.get(self.url('editor', self.map.id))

        self.assertContains(resp, 'Closed Chest Item')
        self.assertContains(resp, 'Danger Marker')
        # MAP_TILE não entra na lib de token; terreno usa a paleta fixa.
        self.assertNotContains(resp, 'Road Tile')

    def test_live_fragment_serializes_terrain_and_token_rotation(self):
        from tabletop.models import TerrainCell
        TerrainCell.objects.create(Map=self.map, Q=1, R=-2, Terrain='grass')
        Token.objects.create(Map=self.map, Kind=Token.ENEMY, Rotation=90, X=0, Y=0)
        resp = self.client.get(self.url('live-fragment'))
        import json
        body = json.loads(resp.content)
        self.assertEqual(body['terrain'], [{'q': 1, 'r': -2, 'terrain': 'grass'}])
        self.assertEqual(body['tokens'][0]['rotation'], 90)


@override_settings(MEDIA_ROOT=tempfile.mkdtemp())
class UploadTests(_Base):
    def test_add_token_with_upload_creates_sprite(self):
        self.client.force_login(self.owner)
        img = SimpleUploadedFile('goblin.png', PNG_1x1, content_type='image/png')
        self.client.post(self.url('add-token'), {
            'MapId': self.map.id, 'Kind': 'enemy', 'Label': 'Bicho', 'SpriteFile': img,
        })
        tok = Token.objects.get(Map=self.map, Label='Bicho')
        self.assertIsNotNone(tok.SpriteAsset)
        self.assertEqual(tok.SpriteAsset.Category, SpriteAsset.MAP_TOKEN)
        self.assertEqual(tok.SpriteAsset.Owner_id, self.owner.id)

    def test_svg_upload_is_rejected(self):
        """SVG carrega <script> → não pode virar SpriteAsset servido na mesma origem."""
        self.client.force_login(self.owner)
        svg = SimpleUploadedFile(
            'evil.svg',
            b'<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>',
            content_type='image/svg+xml',
        )
        self.client.post(self.url('add-token'), {
            'MapId': self.map.id, 'Kind': 'enemy', 'Label': 'Xss', 'SpriteFile': svg,
        })
        tok = Token.objects.get(Map=self.map, Label='Xss')
        self.assertIsNone(tok.SpriteAsset)                      # upload recusado
        self.assertFalse(SpriteAsset.objects.filter(Name='Xss').exists())


class TerrainSeedTests(TestCase):
    def test_texture_slugs_resolve_or_palette_falls_back(self):
        from .views import _terrain_palette_payload
        payload = _terrain_palette_payload(None)
        dungeon = next(t for t in payload if t['id'] == 'dungeon')
        self.assertIn('url', dungeon)        # texturas expõem url (vazia até semear)
        self.assertTrue(dungeon['color'])    # cor de fallback sempre presente
        water = next(t for t in payload if t['id'] == 'water')
        self.assertNotIn('url', water)       # cor sólida não tem url


class ThemeTests(TestCase):
    """Fatia A: paginas da mesa carregam o tema Parchment & Ink."""

    def test_table_view_uses_parchment_theme(self):
        owner = User.objects.create_user('gm', password='x' * 12)
        table = GameTable.objects.create(Owner=owner, Name='Mesa Teste')
        resp = self.client.get(reverse('tabletop:table', args=[table.Slug]))
        self.assertEqual(resp.status_code, 200)
        html = resp.content.decode()
        # classe imersiva no body ativa os tokens parchment
        self.assertIn('tt-themed', html)
        # stylesheet compartilhado dos tokens esta linkado
        self.assertIn('parchment-theme.css', html)


class TerrainModelTests(TestCase):
    def setUp(self):
        self.owner = User.objects.create_user('gmC', password='x' * 12)
        self.table = GameTable.objects.create(Owner=self.owner, Name='Mesa C')
        self.map = Map.objects.create(Table=self.table, Name='Cena')

    def test_token_rotation_defaults_zero(self):
        tok = Token.objects.create(Map=self.map, Kind=Token.ENEMY)
        self.assertEqual(tok.Rotation, 0)

    def test_terrain_cell_unique_per_axial(self):
        from tabletop.models import TerrainCell
        TerrainCell.objects.create(Map=self.map, Q=1, R=-2)
        with self.assertRaises(Exception):
            TerrainCell.objects.create(Map=self.map, Q=1, R=-2)


class EditorEndpointTests(TestCase):
    def setUp(self):
        self.owner = User.objects.create_user('gmE', password='x' * 12)
        self.table = GameTable.objects.create(Owner=self.owner, Name='Mesa E')
        self.map = Map.objects.create(Table=self.table, Name='Cena', GridMode=Map.HEX)
        self.table.ActiveMap = self.map
        self.table.save()
        self.client.force_login(self.owner)

    def test_add_token_with_position_snaps_to_hex(self):
        url = reverse('tabletop:add-token', args=[self.table.Slug])
        resp = self.client.post(url, {'MapId': self.map.id, 'Kind': 'enemy', 'X': 120, 'Y': 90})
        self.assertEqual(resp.status_code, 200)
        tok = Token.objects.filter(Map=self.map).latest('id')
        self.assertEqual((tok.X, tok.Y), nearest_hex_center(120, 90, self.map.GridSize))

    def test_edit_token_sets_rotation(self):
        tok = Token.objects.create(Map=self.map, Kind=Token.ENEMY)
        url = reverse('tabletop:edit-token', args=[self.table.Slug, tok.id])
        self.client.post(url, {'Rotation': 90})
        tok.refresh_from_db()
        self.assertEqual(tok.Rotation, 90)

    def test_move_token_can_update_rotation(self):
        tok = Token.objects.create(Map=self.map, Kind=Token.ENEMY)
        url = reverse('tabletop:move-token', args=[self.table.Slug, tok.id])
        self.client.post(url, {'X': 120, 'Y': 90, 'Rotation': 450})
        tok.refresh_from_db()
        self.assertEqual(tok.Rotation, 90)

    def test_owner_move_from_editor_returns_editor_body(self):
        tok = Token.objects.create(Map=self.map, Kind=Token.ENEMY)
        url = reverse('tabletop:move-token', args=[self.table.Slug, tok.id])
        resp = self.client.post(
            url, {'X': 120, 'Y': 90},
            HTTP_HX_REQUEST='true', HTTP_HX_TARGET='tt-editor',
        )
        self.assertContains(resp, 'id="tt-palette"')
        self.assertContains(resp, 'id="tt-world"')

    def test_paint_terrain_creates_cells(self):
        url = reverse('tabletop:paint-terrain', args=[self.table.Slug, self.map.id])
        resp = self.client.post(url, {'cells': '1,-2;0,0;3,1'})
        self.assertEqual(resp.status_code, 200)
        from tabletop.models import TerrainCell
        self.assertEqual(TerrainCell.objects.filter(Map=self.map).count(), 3)

    def test_paint_terrain_is_idempotent_on_repeat(self):
        url = reverse('tabletop:paint-terrain', args=[self.table.Slug, self.map.id])
        self.client.post(url, {'cells': '1,1'})
        self.client.post(url, {'cells': '1,1'})
        from tabletop.models import TerrainCell
        self.assertEqual(TerrainCell.objects.filter(Map=self.map, Q=1, R=1).count(), 1)

    def test_clear_terrain_deletes_cells(self):
        from tabletop.models import TerrainCell
        TerrainCell.objects.create(Map=self.map, Q=1, R=1)
        TerrainCell.objects.create(Map=self.map, Q=2, R=1)
        url = reverse('tabletop:clear-terrain', args=[self.table.Slug, self.map.id])
        resp = self.client.post(url, {'cells': '1,1'})
        self.assertEqual(resp.status_code, 200)
        self.assertFalse(TerrainCell.objects.filter(Map=self.map, Q=1, R=1).exists())
        self.assertTrue(TerrainCell.objects.filter(Map=self.map, Q=2, R=1).exists())

    def test_paint_terrain_forbidden_for_stranger(self):
        self.client.logout()
        stranger = User.objects.create_user('x', password='x' * 12)
        self.client.force_login(stranger)
        url = reverse('tabletop:paint-terrain', args=[self.table.Slug, self.map.id])
        self.assertEqual(self.client.post(url, {'cells': '1,1'}).status_code, 403)
