import tempfile

from django.contrib.auth.models import User
from django.core.files.uploadedfile import SimpleUploadedFile
from django.test import SimpleTestCase, TestCase, override_settings
from django.urls import reverse

from sprites.models import SpriteAsset

from .calculations import point_in_rect, snap_to_grid, token_visible_to
from .models import FogRegion, GameTable, Map, Token


# 1x1 PNG válido (Pillow lê dimensões; sem Pillow, o upload ainda funciona).
PNG_1x1 = (
    b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01\x08\x06'
    b'\x00\x00\x00\x1f\x15\xc4\x89\x00\x00\x00\nIDATx\x9cc\x00\x01\x00\x00\x05'
    b'\x00\x01\r\n-\xb4\x00\x00\x00\x00IEND\xaeB`\x82'
)


class _Tok:
    """Stub leve p/ testar token_visible_to sem tocar o DB."""
    def __init__(self, x, y, hidden=False):
        self.X, self.Y, self.Hidden = x, y, hidden


class _Fog:
    def __init__(self, x, y, w, h):
        self.X, self.Y, self.Width, self.Height = x, y, w, h


class CalcTests(SimpleTestCase):
    def test_snap_square_centers_in_cell(self):
        self.assertEqual(snap_to_grid(100, 30, 64, 'square'), (96, 32))
        self.assertEqual(snap_to_grid(0, 0, 64, 'square'), (32, 32))

    def test_snap_free_is_identity(self):
        self.assertEqual(snap_to_grid(123, 77, 64, 'free'), (123, 77))

    def test_snap_without_size_is_identity(self):
        self.assertEqual(snap_to_grid(123, 77, 0, 'square'), (123, 77))

    def test_point_in_rect(self):
        self.assertTrue(point_in_rect(50, 50, 0, 0, 100, 100))
        self.assertFalse(point_in_rect(150, 50, 0, 0, 100, 100))

    def test_visibility_owner_sees_everything(self):
        self.assertTrue(token_visible_to(_Tok(50, 50, hidden=True), [_Fog(0, 0, 100, 100)], True))

    def test_visibility_player_hidden_and_under_fog(self):
        self.assertFalse(token_visible_to(_Tok(10, 10, hidden=True), [], False))
        self.assertFalse(token_visible_to(_Tok(50, 50), [_Fog(0, 0, 100, 100)], False))
        self.assertTrue(token_visible_to(_Tok(500, 500), [_Fog(0, 0, 100, 100)], False))


class ModelTests(TestCase):
    def setUp(self):
        self.owner = User.objects.create_user('owner', password='x' * 12)

    def test_slug_autogenerated_and_unique(self):
        a = GameTable.objects.create(Owner=self.owner, Name='A')
        b = GameTable.objects.create(Owner=self.owner, Name='B')
        self.assertTrue(a.Slug and b.Slug)
        self.assertNotEqual(a.Slug, b.Slug)

    def test_default_movable_by_kind(self):
        self.assertTrue(Token.default_movable_for_kind(Token.PLAYER))
        self.assertFalse(Token.default_movable_for_kind(Token.ENEMY))
        self.assertFalse(Token.default_movable_for_kind(Token.OBJECT))


class _Base(TestCase):
    def setUp(self):
        self.owner = User.objects.create_user('owner', password='x' * 12)
        self.stranger = User.objects.create_user('stranger', password='x' * 12)
        self.table = GameTable.objects.create(Owner=self.owner, Name='Mesa')
        self.map = Map.objects.create(Table=self.table, Name='Cena', GridMode=Map.SQUARE, GridSize=64)
        self.table.ActiveMap = self.map
        self.table.save()

    def url(self, name, *args):
        return reverse('tabletop:' + name, args=[self.table.Slug, *args])


class PermissionTests(_Base):
    def test_table_view_public(self):
        resp = self.client.get(self.url('table'))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, 'Mesa')

    def test_manage_requires_owner(self):
        self.assertEqual(self.client.get(self.url('manage')).status_code, 403)  # anônimo
        self.client.force_login(self.stranger)
        self.assertEqual(self.client.get(self.url('manage')).status_code, 403)
        self.client.force_login(self.owner)
        self.assertEqual(self.client.get(self.url('manage')).status_code, 200)

    def test_add_map_owner_only(self):
        self.assertEqual(self.client.post(self.url('add-map'), {'Name': 'X'}).status_code, 403)
        self.client.force_login(self.owner)
        self.client.post(self.url('add-map'), {'Name': 'Nova', 'GridMode': 'free'})
        self.assertTrue(Map.objects.filter(Table=self.table, Name='Nova').exists())

    def test_set_active_switches_scene(self):
        self.client.force_login(self.owner)
        other = Map.objects.create(Table=self.table, Name='Outra')
        self.client.post(self.url('set-active', other.id))
        self.table.refresh_from_db()
        self.assertEqual(self.table.ActiveMap_id, other.id)


class TokenTests(_Base):
    def test_add_player_token_movable_by_default(self):
        self.client.force_login(self.owner)
        self.client.post(self.url('add-token'), {'MapId': self.map.id, 'Kind': 'player', 'Label': 'Heroi'})
        tok = Token.objects.get(Map=self.map, Label='Heroi')
        self.assertTrue(tok.MovableByPlayers)
        self.assertEqual(tok.Kind, Token.PLAYER)

    def test_add_enemy_token_not_movable(self):
        self.client.force_login(self.owner)
        self.client.post(self.url('add-token'), {'MapId': self.map.id, 'Kind': 'enemy'})
        self.assertFalse(Token.objects.get(Map=self.map).MovableByPlayers)


class MoveTests(_Base):
    def _player_token(self, movable=True, on_active=True):
        m = self.map if on_active else Map.objects.create(Table=self.table, Name='Inativa')
        return Token.objects.create(Map=m, Kind=Token.PLAYER, MovableByPlayers=movable, X=10, Y=10)

    def test_owner_moves_any_token_and_snaps(self):
        self.client.force_login(self.owner)
        tok = Token.objects.create(Map=self.map, Kind=Token.ENEMY, X=0, Y=0)
        resp = self.client.post(self.url('move-token', tok.id), {'X': 100, 'Y': 30})
        self.assertEqual(resp.status_code, 200)
        tok.refresh_from_db()
        self.assertEqual((tok.X, tok.Y), (96, 32))  # snap em grade 64

    def test_anonymous_moves_movable_token_on_active_map(self):
        tok = self._player_token(movable=True, on_active=True)
        resp = self.client.post(self.url('move-token', tok.id), {'X': 200, 'Y': 200})
        self.assertEqual(resp.status_code, 200)
        tok.refresh_from_db()
        self.assertEqual((tok.X, tok.Y), (224, 224))

    def test_anonymous_cannot_move_enemy(self):
        tok = Token.objects.create(Map=self.map, Kind=Token.ENEMY, MovableByPlayers=False, X=0, Y=0)
        self.assertEqual(self.client.post(self.url('move-token', tok.id), {'X': 50, 'Y': 50}).status_code, 403)

    def test_anonymous_cannot_move_token_on_inactive_map(self):
        tok = self._player_token(movable=True, on_active=False)
        self.assertEqual(self.client.post(self.url('move-token', tok.id), {'X': 50, 'Y': 50}).status_code, 403)


class VisibilityTests(_Base):
    def test_player_fragment_hides_fogged_and_hidden_tokens(self):
        FogRegion.objects.create(Map=self.map, X=0, Y=0, Width=200, Height=200)
        Token.objects.create(Map=self.map, Kind=Token.ENEMY, Label='Goblin', X=50, Y=50)       # sob névoa
        Token.objects.create(Map=self.map, Kind=Token.ENEMY, Label='Espreita', X=400, Y=400, Hidden=True)
        Token.objects.create(Map=self.map, Kind=Token.PLAYER, Label='Aragorn', X=400, Y=400)    # visível

        anon = self.client.get(self.url('live-fragment'))
        self.assertNotContains(anon, 'Goblin')
        self.assertNotContains(anon, 'Espreita')
        self.assertContains(anon, 'Aragorn')

        self.client.force_login(self.owner)
        owner = self.client.get(self.url('live-fragment'))
        self.assertContains(owner, 'Goblin')
        self.assertContains(owner, 'Espreita')


class RenderTests(_Base):
    def test_table_view_is_full_page_fragment_is_partial(self):
        full = self.client.get(self.url('table'))
        self.assertContains(full, 'app-nav')              # estende main.html
        frag = self.client.get(self.url('live-fragment'))
        self.assertNotContains(frag, 'app-nav')           # só o canvas
        self.assertContains(frag, 'tt-canvas')

    def test_owner_pages_render(self):
        self.client.force_login(self.owner)
        self.assertEqual(self.client.get(reverse('tabletop:home')).status_code, 200)
        self.assertEqual(self.client.get(self.url('editor', self.map.id)).status_code, 200)


@override_settings(MEDIA_ROOT=tempfile.mkdtemp())
class UploadTests(_Base):
    def test_add_token_with_upload_creates_sprite(self):
        self.client.force_login(self.owner)
        img = SimpleUploadedFile('goblin.png', PNG_1x1, content_type='image/png')
        self.client.post(self.url('add-token'), {
            'MapId': self.map.id, 'Kind': 'enemy', 'Label': 'Bicho', 'SpriteFile': img,
        })
        tok = Token.objects.get(Map=self.map, Label='Bicho')
        self.assertIsNotNone(tok.SpriteAsset)
        self.assertEqual(tok.SpriteAsset.Category, SpriteAsset.MAP_TOKEN)
        self.assertEqual(tok.SpriteAsset.Owner_id, self.owner.id)

    def test_svg_upload_is_rejected(self):
        """SVG carrega <script> → não pode virar SpriteAsset servido na mesma origem."""
        self.client.force_login(self.owner)
        svg = SimpleUploadedFile(
            'evil.svg',
            b'<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>',
            content_type='image/svg+xml',
        )
        self.client.post(self.url('add-token'), {
            'MapId': self.map.id, 'Kind': 'enemy', 'Label': 'Xss', 'SpriteFile': svg,
        })
        tok = Token.objects.get(Map=self.map, Label='Xss')
        self.assertIsNone(tok.SpriteAsset)                      # upload recusado
        self.assertFalse(SpriteAsset.objects.filter(Name='Xss').exists())
