services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate &&
             gunicorn dd3esheet.wsgi:application --bind 0.0.0.0:8000 --workers 3 --access-logfile -"
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 3s
      retries: 3
