from django.contrib.auth.models import User
from django.test import TestCase
from django.urls import reverse

from .models import Combatant, Encounter

HTMX = {'HX-Request': 'true'}


class EncounterModelTests(TestCase):
    def setUp(self):
        self.user = User.objects.create_user(username='mestre', password='pw')

    def test_slug_is_autogenerated_on_create(self):
        enc = Encounter.objects.create(Owner=self.user)
        self.assertTrue(enc.Slug)
        self.assertGreaterEqual(len(enc.Slug), 16)

    def test_slugs_are_unique_across_encounters(self):
        a = Encounter.objects.create(Owner=self.user)
        b = Encounter.objects.create(Owner=self.user)
        self.assertNotEqual(a.Slug, b.Slug)

    def test_explicit_slug_is_preserved(self):
        enc = Encounter.objects.create(Owner=self.user, Slug='fixo-123')
        self.assertEqual(enc.Slug, 'fixo-123')

    def test_round_defaults_to_one(self):
        enc = Encounter.objects.create(Owner=self.user)
        self.assertEqual(enc.Round, 1)


class CombatantModelTests(TestCase):
    def setUp(self):
        self.user = User.objects.create_user(username='mestre', password='pw')
        self.enc = Encounter.objects.create(Owner=self.user)

    def test_combatants_order_by_initiative_desc(self):
        slow = Combatant.objects.create(Encounter=self.enc, Name='Lento', Initiative=2)
        fast = Combatant.objects.create(Encounter=self.enc, Name='Rapido', Initiative=18)
        mid = Combatant.objects.create(Encounter=self.enc, Name='Medio', Initiative=10)
        ordered = list(self.enc.combatant_set.all())
        self.assertEqual(ordered, [fast, mid, slow])

    def test_damage_taken_defaults_to_zero(self):
        c = Combatant.objects.create(Encounter=self.enc, Name='Goblin')
        self.assertEqual(c.DamageTaken, 0)

    def test_kind_defaults_to_enemy(self):
        c = Combatant.objects.create(Encounter=self.enc, Name='Goblin')
        self.assertEqual(c.Kind, Combatant.ENEMY)


class HomeAndCreateTests(TestCase):
    def setUp(self):
        self.user = User.objects.create_user(username='mestre', password='pw')

    def test_home_requires_login(self):
        resp = self.client.get(reverse('initiative:home'))
        self.assertEqual(resp.status_code, 302)
        self.assertIn('/accounts/login/', resp['Location'])

    def test_home_lists_only_own_encounters(self):
        mine = Encounter.objects.create(Owner=self.user, Name='Minha Mesa')
        other = User.objects.create_user(username='outro', password='pw')
        Encounter.objects.create(Owner=other, Name='Mesa Alheia')
        self.client.force_login(self.user)
        resp = self.client.get(reverse('initiative:home'))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, 'Minha Mesa')
        self.assertNotContains(resp, 'Mesa Alheia')

    def test_create_encounter_requires_login(self):
        resp = self.client.post(reverse('initiative:create-encounter'))
        self.assertEqual(resp.status_code, 302)
        self.assertEqual(Encounter.objects.count(), 0)

    def test_create_encounter_makes_owned_encounter_and_redirects_to_board(self):
        self.client.force_login(self.user)
        resp = self.client.post(reverse('initiative:create-encounter'), {'Name': 'Boss Fight'})
        self.assertEqual(Encounter.objects.count(), 1)
        enc = Encounter.objects.get()
        self.assertEqual(enc.Owner, self.user)
        self.assertEqual(enc.Name, 'Boss Fight')
        self.assertRedirects(resp, reverse('initiative:board', args=[enc.Slug]))


class BoardAccessTests(TestCase):
    def setUp(self):
        self.owner = User.objects.create_user(username='mestre', password='pw')
        self.enc = Encounter.objects.create(Owner=self.owner, Name='Mesa')

    def test_board_is_public_via_slug(self):
        resp = self.client.get(reverse('initiative:board', args=[self.enc.Slug]))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, 'Mesa')

    def test_board_invalid_slug_404(self):
        resp = self.client.get(reverse('initiative:board', args=['nao-existe']))
        self.assertEqual(resp.status_code, 404)

    def test_fragment_is_public_via_slug(self):
        resp = self.client.get(reverse('initiative:board-fragment', args=[self.enc.Slug]))
        self.assertEqual(resp.status_code, 200)

    def test_anonymous_viewer_sees_no_edit_controls(self):
        resp = self.client.get(reverse('initiative:board', args=[self.enc.Slug]))
        self.assertNotContains(resp, 'data-role="gm-controls"')

    def test_owner_sees_edit_controls(self):
        self.client.force_login(self.owner)
        resp = self.client.get(reverse('initiative:board', args=[self.enc.Slug]))
        self.assertContains(resp, 'data-role="gm-controls"')


class EditPermissionTests(TestCase):
    def setUp(self):
        self.owner = User.objects.create_user(username='mestre', password='pw')
        self.stranger = User.objects.create_user(username='estranho', password='pw')
        self.enc = Encounter.objects.create(Owner=self.owner, Name='Mesa')

    def _add_url(self):
        return reverse('initiative:add-combatant', args=[self.enc.Slug])

    def test_anonymous_cannot_add_combatant(self):
        resp = self.client.post(self._add_url(), {'Name': 'Intruso'}, headers=HTMX)
        self.assertIn(resp.status_code, (302, 403))
        self.assertEqual(Combatant.objects.count(), 0)

    def test_non_owner_cannot_add_combatant(self):
        self.client.force_login(self.stranger)
        resp = self.client.post(self._add_url(), {'Name': 'Intruso'}, headers=HTMX)
        self.assertEqual(resp.status_code, 403)
        self.assertEqual(Combatant.objects.count(), 0)


class CombatantEditTests(TestCase):
    def setUp(self):
        self.owner = User.objects.create_user(username='mestre', password='pw')
        self.enc = Encounter.objects.create(Owner=self.owner, Name='Mesa')
        self.client.force_login(self.owner)

    def test_add_combatant_creates_and_orders_by_initiative(self):
        self.client.post(reverse('initiative:add-combatant', args=[self.enc.Slug]),
                         {'Name': 'Lento', 'Kind': 'enemy', 'Initiative': '3'}, headers=HTMX)
        self.client.post(reverse('initiative:add-combatant', args=[self.enc.Slug]),
                         {'Name': 'Rapido', 'Kind': 'player', 'Initiative': '20'}, headers=HTMX)
        names = list(self.enc.combatant_set.values_list('Name', flat=True))
        self.assertEqual(names, ['Rapido', 'Lento'])

    def test_apply_damage_accumulates(self):
        c = Combatant.objects.create(Encounter=self.enc, Name='Goblin')
        url = reverse('initiative:apply-damage', args=[self.enc.Slug, c.id])
        self.client.post(url, {'delta': '5'}, headers=HTMX)
        self.client.post(url, {'delta': '3'}, headers=HTMX)
        c.refresh_from_db()
        self.assertEqual(c.DamageTaken, 8)

    def test_apply_damage_clamps_at_zero(self):
        c = Combatant.objects.create(Encounter=self.enc, Name='Goblin', DamageTaken=4)
        url = reverse('initiative:apply-damage', args=[self.enc.Slug, c.id])
        self.client.post(url, {'delta': '-10'}, headers=HTMX)
        c.refresh_from_db()
        self.assertEqual(c.DamageTaken, 0)

    def test_damage_total_shown_on_board(self):
        c = Combatant.objects.create(Encounter=self.enc, Name='Goblin', DamageTaken=7)
        resp = self.client.get(reverse('initiative:board-fragment', args=[self.enc.Slug]))
        self.assertContains(resp, '7')

    def test_edit_combatant_saves_effects_and_notes(self):
        c = Combatant.objects.create(Encounter=self.enc, Name='Goblin')
        url = reverse('initiative:edit-combatant', args=[self.enc.Slug, c.id])
        self.client.post(url, {'Name': 'Goblin', 'Kind': 'enemy', 'Initiative': '5',
                               'Effects': 'Envenenado', 'Notes': 'Foge aos 5 HP',
                               'ArmorClass': '15'}, headers=HTMX)
        c.refresh_from_db()
        self.assertEqual(c.Effects, 'Envenenado')
        self.assertEqual(c.Notes, 'Foge aos 5 HP')
        self.assertEqual(c.ArmorClass, 15)

    def test_delete_combatant_removes_it(self):
        c = Combatant.objects.create(Encounter=self.enc, Name='Goblin')
        url = reverse('initiative:delete-combatant', args=[self.enc.Slug, c.id])
        self.client.post(url, headers=HTMX)
        self.assertFalse(Combatant.objects.filter(id=c.id).exists())

    def test_deleting_active_combatant_clears_pointer(self):
        c = Combatant.objects.create(Encounter=self.enc, Name='Goblin')
        self.enc.ActiveCombatant = c
        self.enc.save()
        self.client.post(reverse('initiative:delete-combatant', args=[self.enc.Slug, c.id]),
                         headers=HTMX)
        self.enc.refresh_from_db()
        self.assertIsNone(self.enc.ActiveCombatant)


class TurnTests(TestCase):
    def setUp(self):
        self.owner = User.objects.create_user(username='mestre', password='pw')
        self.enc = Encounter.objects.create(Owner=self.owner, Name='Mesa')
        self.client.force_login(self.owner)
        self.fast = Combatant.objects.create(Encounter=self.enc, Name='Rapido', Initiative=20)
        self.slow = Combatant.objects.create(Encounter=self.enc, Name='Lento', Initiative=5)

    def test_next_turn_advances_through_initiative_order(self):
        url = reverse('initiative:next-turn', args=[self.enc.Slug])
        self.client.post(url, headers=HTMX)
        self.enc.refresh_from_db()
        self.assertEqual(self.enc.ActiveCombatant, self.fast)
        self.assertEqual(self.enc.Round, 1)
        self.client.post(url, headers=HTMX)
        self.enc.refresh_from_db()
        self.assertEqual(self.enc.ActiveCombatant, self.slow)
        self.assertEqual(self.enc.Round, 1)

    def test_next_turn_wraps_and_increments_round(self):
        url = reverse('initiative:next-turn', args=[self.enc.Slug])
        self.client.post(url, headers=HTMX)  # fast
        self.client.post(url, headers=HTMX)  # slow
        self.client.post(url, headers=HTMX)  # wrap -> fast, round 2
        self.enc.refresh_from_db()
        self.assertEqual(self.enc.ActiveCombatant, self.fast)
        self.assertEqual(self.enc.Round, 2)

    def test_reset_turn_clears_pointer_and_round(self):
        next_url = reverse('initiative:next-turn', args=[self.enc.Slug])
        self.client.post(next_url, headers=HTMX)
        self.client.post(next_url, headers=HTMX)
        self.client.post(next_url, headers=HTMX)  # round 2
        self.client.post(reverse('initiative:reset-turn', args=[self.enc.Slug]), headers=HTMX)
        self.enc.refresh_from_db()
        self.assertEqual(self.enc.Round, 1)
        self.assertIsNone(self.enc.ActiveCombatant)


class SpriteTests(TestCase):
    def setUp(self):
        self.owner = User.objects.create_user(username='mestre', password='pw')
        self.enc = Encounter.objects.create(Owner=self.owner, Name='Mesa')

    def test_board_marks_each_kind_distinctly(self):
        Combatant.objects.create(Encounter=self.enc, Name='Heroi', Kind=Combatant.PLAYER, Initiative=15)
        Combatant.objects.create(Encounter=self.enc, Name='Ferreiro', Kind=Combatant.NPC, Initiative=10)
        Combatant.objects.create(Encounter=self.enc, Name='Goblin', Kind=Combatant.ENEMY, Initiative=5)
        resp = self.client.get(reverse('initiative:board-fragment', args=[self.enc.Slug]))
        self.assertContains(resp, 'init-token--player')
        self.assertContains(resp, 'init-token--npc')
        self.assertContains(resp, 'init-token--enemy')
